### PR TITLE
Update drop_index.md

### PR DESCRIPTION
**Pull request by arthuo**
Overwrite with new ones_zh

### CODE REVIEW

**Comment by LocoRichard** [comment]
Hi @arthuo , Thank you so much for your contribution. Please check out the necessary feedbacks I've made to the translation. The PR is good to be merged as soon as they are resolved.

**Comment by arthuo** [comment]
> Hi @arthuo , Thank you so much for your contribution. Please check out the necessary feedbacks I've made to the translation. The PR is good to be merged as soon as they are resolved.

Hi, thank you for your reply. I checked the feedback, but unfortunately I didn't find it.

**Review by LocoRichard — CHANGES_REQUESTED** [review]

**Comment by LocoRichard** [comment]
> > Hi @arthuo , Thank you so much for your contribution. Please check out the necessary feedbacks I've made to the translation. The PR is good to be merged as soon as they are resolved.
> 
> Hi, thank you for your reply. I checked the feedback, but unfortunately I didn't find it.

Sorry that I forgot to request change, can you see them now?

**Comment by arthuo** [comment]
> > > Hi @arthuo , Thank you so much for your contribution. Please check out the necessary feedbacks I've made to the translation. The PR is good to be merged as soon as they are resolved.
> > 
> > 
> > Hi, thank you for your reply. I checked the feedback, but unfortunately I didn't find it.
> 
> Sorry that I forgot to request change, can you see them now?

Yes, it can be seen now. I have made the corresponding changes based on the feedback you gave, can you see my changes?

**Comment by LocoRichard** [comment]
Thank you @arthuo , I think your contribution meets our requirements. Check other pages that need translation if you are still interested in contributing to us. Merging your PR.

**Pull request merged**
