### PR TITLE
Getir adopted Milvus in production to improve its neural search engine !

### PR DESCRIPTION
**Pull request by mpolatcan**

### CODE REVIEW

**Comment by claireyuw** [comment]
Hi @mpolatcan, thank you for letting us know! Would you be interested in drafting a user story for our [blog](https://zilliz.com/blog?tag=1)?

**Review by claireyuw — APPROVED** [review]

**Review by claireyuw — APPROVED** [review]

**Comment by mpolatcan** [comment]
Hi @claireyuw , we don't have prepared blog post yet but we think :)

**Review by LocoRichard — APPROVED** [review]

**Comment by LocoRichard** [comment]
Thank you @mpolatcan ! Your PR has been merged. We are looking forward to your blog article!

**Comment by claireyuw** [comment]
@mpolatcan Perfect! Once it is ready, you can submit it by [opening an issue in the Milvus community repo](https://github.com/milvus-io/community/issues/new). Cheers :)

**Comment by mpolatcan** [comment]
Thanks @claireyuw @LocoRichard :) 👍  When we can see our company on Milvus Adopters page https://milvus.io/docs/v2.0.0/milvus_adopters.md ?

**Comment by claireyuw** [comment]
@mpolatcan We just released the update. You should be able to see it shortly!

**Comment by claireyuw** [comment]
@mpolatcan Hi! How's the article going?

**Pull request merged**
