### PR TITLE
Deleted PyMilvus FAQ from Doc  : Hacktoberfest

### PR DESCRIPTION
**Pull request by iamartyaa**
Issue: #909 

Deleted pymilvus_faq.md from EN & zh-CN directories as PyMilvus API has its own FAQ page.

### CODE REVIEW

**Comment by iamartyaa** [comment]
Please review it @claireyuw

**Comment by LocoRichard** [comment]
Hi @iamartyaa . By changing the menustructure, I didn't mean to rename any of the files. This is a rather complicated issue that is not for contributors. We really appreciate your contribution, but I don't think you can take on this issue. Please find some other hacktoberfest-labelled issues that suit you if you are still interested.

**Comment by iamartyaa** [comment]
Please review it now @LocoRichard .

**Comment by iamartyaa** [comment]
Hey @LocoRichard ,
I understood the menustructure and modified the en.json & cn.json files accordingly. If there are still some changes to be made then I am willing to do so.
If the issue is resolved then can you please merge this PR with the 'Hacktoberfest-accepted' label?

If you still insist I shouldn't be taking on this issue then I will look for some other 'Hacktoberfest-labelled' issues on milvus.

**Comment by LocoRichard** [comment]
@iamartyaa I can't really say no to an active contributor, can I?
截屏2021-10-19 17 27 49
 
截屏2021-10-19 17 28 33
I have marked the parts you need to delete in the red square, please delete them and the menustructure will be correct.
Thank you for your patience.

**Comment by iamartyaa** [comment]
I have made the changes. Thank you for helping me out and for providing such clear instructions @LocoRichard .

**Pull request merged**
